### ISSUE TITLE
which status register to use?

### ISSUE THREAD

**Issue by fguptill** [rickkas7/LIS3DH#3]
The function "getSample" checks the status of REG_STATUS_AUX before it updates the acceleration sample object.
REG_STATUS_AUX reflects the status of the auxiliary ADC ports.
It might be better if update of the sample object were dependent upon the content of REG_STATUS_REG, which reflects the status of the acceleration data.

bool LIS3DH::getSample(LIS3DHSample &sample) {
	uint8_t statusAuxReg = readRegister8(REG_STATUS_AUX);

	bool hasData = ((statusAuxReg & STATUS_AUX_321DA) != 0);

	if (hasData) {
		uint8_t resp[6];
		readData(REG_OUT_X_L, resp, sizeof(resp));

		sample.x = (int16_t) (resp[0] | (((uint16_t)resp[1]) << 8));
		sample.y = (int16_t) (resp[2] | (((uint16_t)resp[3]) << 8));
		sample.z = (int16_t) (resp[4] | (((uint16_t)resp[5]) << 8));
	}
	return hasData;
}

**Comment by fguptill** [comment]
I have made the above change in my code and it seems to be working fine.

**Comment by rickkas7** [comment]
Fixed in version 0.2.3
