### ISSUE TITLE
Temperature Reading is 0

### ISSUE THREAD

**Issue by bryansosa** [rickkas7/LIS3DH#4]
When trying to read the temperature I get 0.

I am doing the following:

```
LIS3DHConfig config;
config.setLowPowerWakeMode(16);
		
boolean accelConfig = accel.setup(config);
accel.enableTemperature(true);

.
.
.
.

int16_t  temp = accel.getTemperature();
```

Am I missing something?

**Comment by rickkas7** [comment]
That should work, as long as there's a few seconds between the time you call enableTemperature and get the temperature. It seems to take a while to initialize, and returns 0 when there's no value yet.

Also, it's really inaccurate. I found it to be frequently off by more than 10°C.

**Comment by bryansosa** [comment]
I've put a 5 second delay after` accel.enableTemperature(true);` and still does not work.

I feel like I'm missing something.

My temperature readings do not need to be pretty accurate.

Thanks a lot for your help!

**Comment by rickkas7** [comment]
Closing since there hasn't been any activity, feel free to reopen if necessary.
